-- Add missing Product columns to fix 500 error
-- Run this in your MySQL database

ALTER TABLE products 
ADD COLUMN IF NOT EXISTS sender VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sender_phone VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sender_email VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sender_address TEXT NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS receiver_name VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS receiver_phone VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS receiver_email VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS receiver_address TEXT NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS discount DECIMAL(10,2) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS remaining DECIMAL(10,2) NULL DEFAULT NULL;
